# Generated by Django 5.1.3 on 2024-11-22 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_wishlist_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='seller',
        ),
    ]
