# Generated by Django 5.1.3 on 2024-11-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_item_transaction_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Home', 'Home'), ('Collectibles', 'Collectibles'), ('Clothing, Shoes & Accessories', 'Clothing, Shoes & Accessories'), ('Sporting Goods', 'Sporting Goods'), ('Jewelry & Watches', 'Jewelry & Watches'), ('Business & Industrial', 'Business & Industrial')], default='Electronics', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Like New', 'Like New'), ('Good', 'Good'), ('Acceptable', 'Acceptable'), ('Poor', 'Poor')], default='New', max_length=50),
        ),
    ]
