# Generated by Django 5.1.2 on 2024-10-21 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0005_alter_image_image_file_alter_image_status_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='status_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_fb.statusmessage'),
        ),
    ]
