# Generated by Django 5.1.3 on 2024-11-22 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0015_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmessage',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='st', to='mini_fb.profile'),
        ),
    ]
